
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:63 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/opt/local/bin/"
      - "/opt/local/sbin/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/Library/Apple/usr/bin/"
      - "/Applications/VMware Fusion.app/Contents/Public/"
      - "/usr/local/share/dotnet/"
      - "/Users/timothyfelt/Lab04_Tim_Ben/~/.dotnet/tools/"
      - "/Library/Frameworks/Mono.framework/Versions/Current/Commands/"
    searched_directories:
      - "/opt/local/bin/uname"
      - "/opt/local/sbin/uname"
      - "/opt/homebrew/bin/uname"
      - "/opt/homebrew/sbin/uname"
      - "/usr/local/bin/uname"
      - "/System/Cryptexes/App/usr/bin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/opt/local/bin"
        - "/opt/local/sbin"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/Library/Apple/usr/bin"
        - "/Applications/VMware Fusion.app/Contents/Public"
        - "/usr/local/share/dotnet"
        - "~/.dotnet/tools"
        - "/Library/Frameworks/Mono.framework/Versions/Current/Commands"
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:63 (project)"
    message: |
      The system is: Darwin - 24.6.0 - arm64
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeNinjaFindMake.cmake:5 (find_program)"
      - "CMakeLists.txt:63 (project)"
    mode: "program"
    variable: "CMAKE_MAKE_PROGRAM"
    description: "Program used to build from build.ninja files."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "ninja-build"
      - "ninja"
      - "samu"
    candidate_directories:
      - "/opt/local/bin/"
      - "/opt/local/sbin/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/Library/Apple/usr/bin/"
      - "/Applications/VMware Fusion.app/Contents/Public/"
      - "/usr/local/share/dotnet/"
      - "/Users/timothyfelt/Lab04_Tim_Ben/~/.dotnet/tools/"
      - "/Library/Frameworks/Mono.framework/Versions/Current/Commands/"
    searched_directories:
      - "/opt/local/bin/ninja-build"
      - "/opt/local/bin/ninja"
      - "/opt/local/bin/samu"
      - "/opt/local/sbin/ninja-build"
      - "/opt/local/sbin/ninja"
      - "/opt/local/sbin/samu"
      - "/opt/homebrew/bin/ninja-build"
      - "/opt/homebrew/bin/ninja"
      - "/opt/homebrew/bin/samu"
      - "/opt/homebrew/sbin/ninja-build"
      - "/opt/homebrew/sbin/ninja"
      - "/opt/homebrew/sbin/samu"
      - "/usr/local/bin/ninja-build"
      - "/usr/local/bin/ninja"
      - "/usr/local/bin/samu"
      - "/System/Cryptexes/App/usr/bin/ninja-build"
      - "/System/Cryptexes/App/usr/bin/ninja"
      - "/System/Cryptexes/App/usr/bin/samu"
      - "/usr/bin/ninja-build"
      - "/usr/bin/ninja"
      - "/usr/bin/samu"
      - "/bin/ninja-build"
      - "/bin/ninja"
      - "/bin/samu"
      - "/usr/sbin/ninja-build"
      - "/usr/sbin/ninja"
      - "/usr/sbin/samu"
      - "/sbin/ninja-build"
      - "/sbin/ninja"
      - "/sbin/samu"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/ninja-build"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/ninja"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/samu"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/ninja-build"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/ninja"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/samu"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/ninja-build"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/ninja"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/samu"
      - "/Library/Apple/usr/bin/ninja-build"
      - "/Library/Apple/usr/bin/ninja"
      - "/Library/Apple/usr/bin/samu"
      - "/Applications/VMware Fusion.app/Contents/Public/ninja-build"
      - "/Applications/VMware Fusion.app/Contents/Public/ninja"
      - "/Applications/VMware Fusion.app/Contents/Public/samu"
      - "/usr/local/share/dotnet/ninja-build"
      - "/usr/local/share/dotnet/ninja"
      - "/usr/local/share/dotnet/samu"
      - "/Users/timothyfelt/Lab04_Tim_Ben/~/.dotnet/tools/ninja-build"
      - "/Users/timothyfelt/Lab04_Tim_Ben/~/.dotnet/tools/ninja"
      - "/Users/timothyfelt/Lab04_Tim_Ben/~/.dotnet/tools/samu"
      - "/Library/Frameworks/Mono.framework/Versions/Current/Commands/ninja-build"
      - "/Library/Frameworks/Mono.framework/Versions/Current/Commands/ninja"
      - "/Library/Frameworks/Mono.framework/Versions/Current/Commands/samu"
    found: false
    search_context:
      ENV{PATH}:
        - "/opt/local/bin"
        - "/opt/local/sbin"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/Library/Apple/usr/bin"
        - "/Applications/VMware Fusion.app/Contents/Public"
        - "/usr/local/share/dotnet"
        - "~/.dotnet/tools"
        - "/Library/Frameworks/Mono.framework/Versions/Current/Commands"
...
